// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFXJR2e__-rxU4IMqDO4zq6WF3iWwP0Vw',
    appId: '1:244083738284:web:94110c92543b6dbd370109',
    messagingSenderId: '244083738284',
    projectId: 'flowva-b8d24',
    authDomain: 'flowva-b8d24.firebaseapp.com',
    storageBucket: 'flowva-b8d24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxxYdvJg47Cc8IuRvfl7Q7DRHrABk4-CE',
    appId: '1:244083738284:android:305eebfdfdcb5fe8370109',
    messagingSenderId: '244083738284',
    projectId: 'flowva-b8d24',
    storageBucket: 'flowva-b8d24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxNc5HeSXJ8o-wdxbS42d7i5eVhDX5crg',
    appId: '1:244083738284:ios:41ffa09fa5b91b43370109',
    messagingSenderId: '244083738284',
    projectId: 'flowva-b8d24',
    storageBucket: 'flowva-b8d24.firebasestorage.app',
    iosBundleId: 'com.example.flowva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxNc5HeSXJ8o-wdxbS42d7i5eVhDX5crg',
    appId: '1:244083738284:ios:41ffa09fa5b91b43370109',
    messagingSenderId: '244083738284',
    projectId: 'flowva-b8d24',
    storageBucket: 'flowva-b8d24.firebasestorage.app',
    iosBundleId: 'com.example.flowva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFXJR2e__-rxU4IMqDO4zq6WF3iWwP0Vw',
    appId: '1:244083738284:web:7b79a9b3d927d107370109',
    messagingSenderId: '244083738284',
    projectId: 'flowva-b8d24',
    authDomain: 'flowva-b8d24.firebaseapp.com',
    storageBucket: 'flowva-b8d24.firebasestorage.app',
  );

}

