# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Flowva Local Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - uses: ollama/qwen2.5-coder-7b
  - uses: ollama/llama3.2-3b

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers: []